aspbasic/Models/ErrorViewModel.cs
using System;

namespace aspbasic.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aspbasic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspbasic.Models;
using aspbasic.service;

namespace aspbasic.Controllers
{
    public class HomeController : Controller
    {

        IAspBasicService aspBasicService;
        public HomeController(IAspBasicService _aspBasicService) {
            this.aspBasicService = _aspBasicService;
        }

        public IActionResult Index()
        {
            ViewData["Orders"] = aspBasicService.GetOrders();
            return View();
        }

        public IActionResult Upload()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Fulfill(int id) 
        {
            // ideally in a CRUD this would be a PUT

            aspBasicService.FulfillOrder(id);   
            return Ok();
        }

  
    }
}

aspbasic/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.IO;
using aspbasic.service;
using aspbasic.service.poco;

namespace aspbasic.Controllers
{
    public class UploadController : Controller
    {

        private IAspBasicService aspBasicService;

        public UploadController(IAspBasicService _aspBasicService)
        {
            this.aspBasicService = _aspBasicService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["FileOptions"] = aspBasicService.GetFileTypes();
            return View();
        }


        // basic upload, ideally this would be streamed, cleanup temp files and have more error checking
        public async Task<IActionResult> UploadFile(List<IFormFile> files, string fileType)
        {
            // based on MSDN example
            long size = files.Sum(f => f.Length);
            var filePath = Path.GetTempFileName();

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            string[] fileLines = aspBasicService.ReadFile(filePath);
            if (aspBasicService.IsFileValid(fileLines, fileType))
            {
                var result = aspBasicService.ImportFile(fileLines, fileType);
                ViewData["UploadResult"] = result;
                return View();
            }
            else
            {
                ViewData["UploadResult"] = new ImportResult()
                {
                    isFatalError = true,
                    errorText = "File is in invalid format"
                };
                return View();
            }

        }
    }
}

aspbasic/Views/Home/Index.cshtml
@using aspbasic.service.poco;

@{
    var orders = (Order[])ViewData["Orders"];
}

<table class="table">

    <thead>
        <tr>
            <th>Customer Id</th>
            <th>Customer Name</th>
            <th>Customer Email</th>
            <th>Study Guides</th>
            <th>Fulfilled</th>
            <th>Date Fulfilled</th>
        </tr>
    </thead>
    <tbody>

        @foreach(Order @order in @orders) 
        {
            <tr>
                <td>@order.customer.customerId</td>
                <td>@order.customer.customerName</td>
                <td>@order.customer.customerEmail</td>
                <td>TBD</td>
                <td><input type="checkbox" checked=@order.fulfilled class="fulfilled" value="@order.orderId" @(@order.fulfilled ? "disabled" : "") /></td>
                <td>@order.dateFulfilled</td>
           </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    window.onload = function() {
        $('.fulfilled').click(function(e){
            var orderId = e.target.value; 
            $.get("/Home/Fulfill/" + orderId).then(function(){
                $(e.target).attr("disabled", true);
                window.location.reload(); // ideally this would be an async updated table... 
            }); // TODO this needs an .error condition that does something smart
        });
    };
</script>

aspbasic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspbasic</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Order List</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Upload" asp-action="">Upload New Orders</a></li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - pf</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>

aspbasic/Views/Upload/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Upload a new file</h2>
<h5>In the interest of time, only the Orders file format is supported at this time.</h5>
<form method="post" enctype="multipart/form-data" asp-controller="Upload" asp-action="UploadFile" id="uploadForm">
    <div class="form-group">
        <div class="row">
            <label>File Type</label>
            <select name="fileType">
                @foreach (var opt in (IEnumerable<string>)@ViewData["FileOptions"]){
                     <option>@opt</option>
                }
            </select>
            <input type="file" name="files"  />
        </div>
         <div class="col-md-10">
            <button id="submitter">Upload</button>
        </div>
    </div>
</form>

aspbasic/Views/Upload/UploadFile.cshtml
@using aspbasic.service.poco;

@{

    var result = (ImportResult)@ViewData["UploadResult"];
}


<h1>Upload Result</h1>


   @if(result.isFatalError){
        <h2 class="text-danger">A fatal error occurred while processing your request.</h2>
   }else {
        <h2>Imported @result.imported </h2>
        <h2>Skipped @result.skipped </h2>
            
   }

   @*
    Outside of fatal because we can get errors on certain rows that are not fatal 
   *@
   @if(!String.IsNullOrEmpty(result.errorText)){
      <h2>Errors that occurred: </h2>
      <h3 class="text-danger">@result.errorText </h3>
   }